### PR TITLE
Allow slice/struct defaults

### PR DESCRIPTION
**Pull request by dim**
I couldn't find a more elegant way for doing this. Feedback is appreciated

### CODE REVIEW

**Comment by vrischmann** [comment]
Hi ! Thanks for the PR. I'll try to take a look today.

**Comment by vrischmann** [comment]
Hi !

sorry for the delay ! I just had a look, and it looks good. It's not a feature I really needed in all my use of envconfig, but it's nice to have it :)
I don't have strong feelings about the separator, `|` is fine with me.

However I think it's a little confusing having to switch between `,` and `|` when writing structs either inside or outside a slice. I'll have to look more in depth.

**Comment by vrischmann** [comment]
Hi,

did you remove the earlier changes from the PR ? It's kinda confusing now looking at the changes.

Anyway, I looked at it more (the first set of changes and your last one) and I can't merge this because both of them might break existing code (someone might use the `|` to parse slices already, same for the options separator).

**Comment by dim** [comment]
So I really think it's a bug fix rather than a feature request. We've had several `default=a,b,c` settings in production only to notice that they were not correctly accepted hours/days later. 

The reason why I'm so keen on this is the fact that it's a mistake easily made. It had quite serious implications for us (twice) and I don't want others to fall into the same trap. It's not something that you can easily cover with unit tests and the notation above seems intuitive to developers.

I have pushed another approach, which requires defaults to be mentioned last. Please let me know if you have a better idea, but I think it's a sensible compromise between backwards compatibility and fixing an ambiguity.

**Comment by vrischmann** [comment]
Ok, maybe I don't exactly understand the problem. What is the bug with `default=a,b` ? Do you mean that you can't easily see which part belongs to the default value and which is the custom key ?

**Comment by dim** [comment]
So yes, we had several cases with:

```go
type Config {
  Tags []string `default=x,y`
}
```

In the production env, we then had `TAGS=x,y,z` but none of them were assigned at all, as `Config.Task` was listening to the `Y` env variable. Similarly, not providing any `TAGS` env var only resulted in `Config.Task` being `[]string{"x"}`

**Comment by vrischmann** [comment]
Ok, I can see how that's confusing. I think the best solution without breaking backwards compatibility is to simply disable parsing defaults when the field is a slice, because it will never work properly.

**Pull request closed without merging**
